# Generated by Django 3.2.9 on 2021-12-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appStore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='inventory',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='price',
        ),
    ]
